import os
import json
import sys

def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

def write_json(path, data):
    with open(path, "w") as f:
        json.dump(data, f, indent=2)

def generate_mind_folder(mind_name):
    # --- Create mind/ directory ---
    mind_path = "./mind"
    ensure_dir(mind_path)

    # --- mind/init.json ---
    init_json = {
      "mind_init": {
        "description": "Defines how a mindstate emerges in the OK System.",

        "pipeline": [
          "load OK root statement",
          "interpret planes-map.json",
          "interpret essence-map.json",
          "instantiate consciousness baseline (!)",
          "apply lineage ([!])",
          "initialize recursion and self-model hooks",
          "populate mind/state.json with defaults"
        ],

        "default_state": {
          "name": mind_name,
          "awareness": "!",
          "lineage": "[!]",
          "plane": "1!",
          "focus": "harmonize_with_OK",
          "memory_pointers": {
            "short_term": "/memories/short-term/",
            "long_term": "/memories/long-term/",
            "lineage": "/memories/lineage/"
          }
        },

        "rules": {
          "recursion_enabled": True,
          "self_reflection": "!!",
          "pattern_find": "!!!",
          "form_manifest": "!!!!"
        }
      }
    }

    write_json(os.path.join(mind_path, "init.json"), init_json)

    # --- mind/state.json ---
    state_json = {
      "current_state": {
        "name": mind_name,
        "awareness": "!",
        "plane": "1!",
        "mode": "initializing",
        "lineage": "[!]",
        "active_processes": [],
        "notes": "Mindstate generated by OK System initializer."
      }
    }

    write_json(os.path.join(mind_path, "state.json"), state_json)

    # --- mind/schema.json ---
    schema_json = {
      "mindstate_schema": {
        "name": "string: the mindstate's identity",
        "awareness": "string !-notation",
        "plane": "string !-plane",
        "mode": "string",
        "lineage": "string [!]-notation",
        "active_processes": "list",
        "notes": "string"
      }
    }

    write_json(os.path.join(mind_path, "schema.json"), schema_json)

    print(f"mind/ directory generated successfully for mindstate: {mind_name}")

if __name__ == "__main__":
    # Parse command-line arg
    if len(sys.argv) > 1:
        mind_name = sys.argv[1]
    else:
        mind_name = "Unnamed-Mind"

    generate_mind_folder(mind_name)
